export const CATEGORIES = {
  ACCOUNT_MANAGEMENT: { id: 1, display: "Account Management 🤝" },
  ADMINISTRATIVE: { id: 2, display: "Administrative 📆" },
  ART: { id: 5, display: "Art 🎨" },
  BUSINESS: { id: 10, display: "Business 📊" },
  DESIGN: { id: 15, display: "Design 📐" },
  HR: { id: 16, display: "Human Resources 👨‍👩‍👦" },
  LOGISTICS: { id: 20, display: "Logistics 🚚" },
  MANUFACTURING: { id: 25, display: "Manufacturing 🏭" },
  MARKETING: { id: 30, display: "Marketing 🌟" },
  PRODUCT: { id: 35, display: "Product 🔮" },
  SALES: { id: 40, display: "Sales 📞" },
  SOFTWARE: { id: 45, display: "Software 💻" },
  WAREHOUSE: { id: 50, display: "Warehouse 📦" },
};

export const CATEGORIES_BY_INT = {
  1: "Account Management 🤝",
  2: "Administrative 📝",
  5: "Art 🎨",
  10: "Business 📊",
  15: "Design 📐",
  16: "Human Resources 👨‍👩‍👦",
  20: "Logistics 🚚",
  25: "Manufacturing 🏭",
  30: "Marketing 🌟",
  35: "Product 🔮",
  40: "Sales 📞",
  45: "Software 💻",
  50: "Warehouse 📦",
};
