export const JAWBS = [
  {
    id: 212,
    company: "Starbucks",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Temp Work"],
    category: "Marketing",
    created: new Date(),
  },
  {
    id: 214,
    company: "Starbucks",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Remote Friendly", "Temp Work"],
    category: "Marketing",
    created: new Date(),
  },
  {
    id: 215,
    company: "Microsoft",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Internship"],
    category: "Marketing",
    created: new Date(),
  },
  {
    id: 218,
    company: "Facebook",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Remote Friendly", "Internship"],
    category: "Marketing",
    created: new Date(),
  },
  {
    id: 220,
    company: "Borger King",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Internship"],
    category: "Marketing",
    created: new Date(),
  },
];
