export const JAWBS = [
  {
    id: 212,
    company: "Starbucks",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Temp"],
    category: 50,
    created: new Date(),
    url: "https://google.com",
  },
  {
    id: 214,
    company: "Starbucks",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Remote Friendly", "Temp"],
    category: 30,
    created: new Date(),
  },
  {
    id: 215,
    company: "Microsoft",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Internship"],
    category: 15,
    created: new Date(),
  },
  {
    id: 218,
    company: "Facebook",
    title: "Marketing Coordinator",
    description:
      "Social media and stuff\nIt is cool and you will have\n... a great time!",
    attributes: ["Remote Friendly", "Internship"],
    category: 30,
    created: new Date(),
  },
  {
    id: 220,
    company: "Borger King",
    title: "Marketing Coordinator",
    description: "Social media and stuff",
    attributes: ["Internship"],
    category: 5,
    created: new Date(),
  },
];
